### PR TITLE
Added FB auth and fixed README

### PR DESCRIPTION
**Pull request by ankitjain28may**
Signed-off-by: Ankit Jain <ankitjain28may77@gmail.com>

### CODE REVIEW

**Comment by itaditya** [comment]
[Add FB auth](https://trello.com/c/kwN3uUsj/5-add-fb-auth)

**Comment by ankitjain28may** [comment]
@itaditya What ?

**Review by itaditya — APPROVED** [review]
Looks good to me, what say @ankitjain28may ?

**Review by ankitjain28may — COMMENTED** [review]
LGTM

**Pull request merged**
